FROM ubuntu:14.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -qq && apt-get install software-properties-common -y && apt-get clean
RUN add-apt-repository ppa:george-edison55/cmake-3.x
RUN apt-get update -qq && \
        apt-get install --no-install-recommends python curl \
        ca-certificates git-core \
        cmake zlib1g-dev build-essential ninja-build -y && \
        apt-get clean
RUN echo 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main' > /etc/apt/sources.list.d/llvm.list
# Fingerprint: 6084 F3CF 814B 57C1 CF12 EFD5 15CF 4D18 AF4F 7421
RUN curl http://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
RUN apt-get update -qq && apt-get install --no-install-recommends clang-3.9 -y && apt-get clean
RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.9 50
RUN update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.9 50
RUN apt-get purge cmake cmake-data -y
RUN curl -o /tmp/cmake.sh https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh \
      && mkdir -p /opt/cmake \
      && yes | bash /tmp/cmake.sh --prefix=/opt/cmake --exclude-subdir \
      && ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake \
      && rm -f /tmp/cmake.sh
RUN /opt/cmake/bin/cmake --version

